import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: "class",
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // From your design system
        surface: '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0edec',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#56423d',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        outline: '#89726c',
        'outline-variant': '#dcc0ba',
        'surface-tint': '#9d422a',
        primary: '#812d17',
        'on-primary': '#ffffff',
        'primary-container': '#a0442c',
        'on-primary-container': '#ffd2c7',
        'inverse-primary': '#ffb4a2',
        secondary: '#875300',
        'on-secondary': '#ffffff',
        'secondary-container': '#fcae4b',
        'on-secondary-container': '#6f4300',
        tertiary: '#325039',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#496850',
        'on-tertiary-container': '#c2e5c7',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdbd2',
        'primary-fixed-dim': '#ffb4a2',
        'on-primary-fixed': '#3c0800',
        'on-primary-fixed-variant': '#7e2b15',
        'secondary-fixed': '#ffddba',
        'secondary-fixed-dim': '#ffb964',
        'on-secondary-fixed': '#2b1700',
        'on-secondary-fixed-variant': '#663e00',
        'tertiary-fixed': '#c8ebcd',
        'tertiary-fixed-dim': '#adcfb2',
        'on-tertiary-fixed': '#03210e',
        'on-tertiary-fixed-variant': '#2f4d37',
        background: '#fcf9f8',
        'on-background': '#1c1b1b',
        'surface-variant': '#e5e2e1',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'container-max': '1280px',
        gutter: '24px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'section-gap-lg': '120px',
        'section-gap-sm': '64px',
      },
      fontFamily: {
        'display-lg': ['"Libre Caslon Text"', 'serif'],
        'display-lg-mobile': ['"Libre Caslon Text"', 'serif'],
        'headline-md': ['"Libre Caslon Text"', 'serif'],
        'headline-sm': ['"Libre Caslon Text"', 'serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        button: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        button: ['16px', { lineHeight: '16px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}

export default config